# -*- coding: utf-8 -*-
"""weel 2 ai/Ml Task 2  DevSphere Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzdU-6k-hvXqbsIL0teOsR_14YmsNBoQ
"""



"""### **Week 2 Task Ai/ML**

## **AI TASK**
"""

import time

print("======================================")
print("   AI WEEK 2 - SEARCH ALGORITHMS")
print("======================================")

def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1


def binary_search(arr, target):
    left = 0
    right = len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1


data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

target = 70

print("\n========== EXAMPLE DATA ==========")
print("Data:", data)
print("Target:", target)

print("\n========== LINEAR SEARCH ==========")

start = time.perf_counter()
linear_result = linear_search(data, target)
linear_time = time.perf_counter() - start

if linear_result != -1:
    print("Target found at index:", linear_result)
else:
    print("Target not found")

print("Time taken:", linear_time, "seconds")

print("\n========== BINARY SEARCH ==========")

start = time.perf_counter()
binary_result = binary_search(data, target)
binary_time = time.perf_counter() - start

if binary_result != -1:
    print("Target found at index:", binary_result)
else:
    print("Target not found")

print("Time taken:", binary_time, "seconds")

print("\n========== PERFORMANCE COMPARISON ==========")

print("Linear Search:")
print("Time Complexity: O(n)")
print("Checks elements one by one.")

print("\nBinary Search:")
print("Time Complexity: O(log n)")
print("Divides the sorted list into smaller parts.")

print("\n========== RESULT ==========")

if linear_result != -1 and binary_result != -1:
    print("Both algorithms successfully found the target.")

if binary_time < linear_time:
    print("Binary Search was faster in this example.")
else:
    print("Linear Search was faster in this example.")

print("\nAI Week 2 Search Algorithms completed successfully!")



"""## **ML Task**"""

import pandas as pd
import matplotlib.pyplot as plt

print("======================================")
print("   ML WEEK 2 - DATA VISUALIZATION")
print("======================================")

df = pd.read_csv("cleaned_students.csv")

print("\nDataset loaded successfully!")

print("\n========== DATA ==========")
print(df)

subject_means = df[["Math", "English", "Science"]].mean()

print("\n========== SUBJECT AVERAGES ==========")
print(subject_means)

print("\n========== INSIGHTS ==========")

highest_subject = subject_means.idxmax()
lowest_subject = subject_means.idxmin()

print(
    "Highest average score:",
    highest_subject,
    "=",
    round(subject_means[highest_subject], 2)
)

print(
    "Lowest average score:",
    lowest_subject,
    "=",
    round(subject_means[lowest_subject], 2)
)

print(
    "Overall average score:",
    round(subject_means.mean(), 2)
)

gender_counts = df["Gender"].value_counts()

print("\nGender distribution:")
print(gender_counts)

print("\n========== BAR CHART ==========")

plt.figure(figsize=(8, 5))

plt.bar(
    subject_means.index,
    subject_means.values
)

plt.title("Average Score by Subject")
plt.xlabel("Subject")
plt.ylabel("Average Score")

plt.tight_layout()
plt.show()


print("\n========== LINE CHART ==========")

plt.figure(figsize=(8, 5))

plt.plot(
    subject_means.index,
    subject_means.values,
    marker="o"
)

plt.title("Average Student Performance")
plt.xlabel("Subject")
plt.ylabel("Average Score")

plt.grid(True)

plt.tight_layout()
plt.show()


print("\n========== PIE CHART ==========")

plt.figure(figsize=(7, 7))

plt.pie(
    gender_counts.values,
    labels=gender_counts.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Student Gender Distribution")

plt.tight_layout()
plt.show()


print("\n======================================")
print("   DATA VISUALIZATION COMPLETED")
print("======================================")

